### ISSUE TITLE
SetCookie fails

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/ldap_sso#1]
I am getting this error quite frequently in the watchdog log.

"Warning: Cannot modify header information - headers already sent in ldap_sso_boot() (line 80 of /modules/ldap_sso/ldap_sso.module)."

Line 80 is setting a cookie for seamless_login_attempted=true.

Any pointers to find what is causing headers to be sent before the hook_boot is complete?

**Comment by kswan** [comment]
I learned that this is related to caching. When I turned off "Cache page for anonymous users" the warning above stopped. For my site the intention is for all visitors to be authenticated so there is no negative effect of this change so I am satisfied that this issue is resolved.

**Comment by VasasA** [comment]
@kswan Thank you very much for the solution!
